# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: touch .env
      - name: Add environment variables to .env file
        run: |
          echo "DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }}" >> .env
          echo "MICROSOFT_API_KEY=${{ secrets.MICROSOFT_API_KEY }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"

#       - name: Create .env file
#         run: touch .env
#       - name: Add environment variables to .env file
#         run: |
#           echo "DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }}" >> .env
#           echo "MICROSOFT_API_KEY=${{ secrets.MICROSOFT_API_KEY }}" >> .env
#           echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
#       - name: Install, build and test
#         run: npm ci
#         run: npm run build --if-present
#         run: npm test
